[package]
version = "0.1.0"

# Global configuration
src = ["src", "tests"]

[libs.math]
lib = "m"

[libs.sdl]
pkg = { sdl2 = "*", SDL2_image = "*", SDL2_ttf = "*", SDL2_mixer = "*" }
lib = ["SDL2main", "SDL2", "SDL2_image", "SDL2_ttf", "SDL2_mixer"]
dir = "lib/{{os}}"
inc = "include/{{os}}"
