/* Generated by updaterev.sh, do not edit */
#define SDL_VENDOR_INFO "Debian 2.26.1+dfsg-1"
#ifdef SDL_VENDOR_INFO
#define SDL_REVISION "SDL-release-2.26.1-0-gf17058b56 (" SDL_VENDOR_INFO ")"
#else
#define SDL_REVISION "SDL-release-2.26.1-0-gf17058b56"
#endif
#define SDL_REVISION_NUMBER 0
